import {
    create,
    NButton,
    NConfigProvider,
    NGlobalStyle,
    NCard,
    NTabs,
    NTabPane,
    NForm,
    NFormItemRow,
    NInput,
    NSwitch,
    NLayout,
    NLayoutHeader,
    NLayoutContent,
    NLayoutSider,
    NLayoutFooter,
    NMenu,
    NGrid,
    NGi,
    NSpace,
    NAvatar,
    NPopselect,
    NIcon,
    NTooltip,
} from 'naive-ui';

const naive = create({
    components: [
        NButton,
        NConfigProvider,
        NGlobalStyle,
        NCard,
        NTabs,
        NTabPane,
        NForm,
        NFormItemRow,
        NInput,
        NSwitch,
        NLayout,
        NLayoutHeader,
        NLayoutContent,
        NLayoutSider,
        NLayoutFooter,
        NMenu,
        NGrid,
        NGi,
        NSpace,
        NAvatar,
        NPopselect,
        NIcon,
        NTooltip,
    ]
})

export default naive